spring:
    application:
        name: tributos
    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
flyway:
    enabled: false
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9090/eureka/
    instance:
        hostname: localhost
        instance-id: http://localhost:8083
server:
    port: 8083