eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
spring:
  application:
    name: gateway
server:
  port: 8080
zuul:
  routes:
    service0: /service/0/**
    service1: /service/1/**
    cadastros: /cadastros/**